sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Ydv7IB+QQ95mX4hRFsUnsFf/EnNYpFtDTTvematvIOBW11RFE5SJjqDduMMQEtU/aj9sTlhwEE3j+7pdJSwmiL49iShGBHnRdY24q6FsfbBjhx4S5PXJYzQ+2PBLAD+MFG0H9DS6mNNzLjZNMPjCE4tGJ/hdKp81Jb0vx6bJD7EvS525ioG12IS8Jd3/aWwM517tbu88ADplJMBdUH/hqyEmppie9VR8vn1IzaAaZ6SgckW+7PjmC16x5pBK89aWMS9ySnbETCuqpOo9nq3yYkVH3fVth9PsjRiXgay24do0rTyBle4q0pbiVKJMBD4xYd0vDAy5cjiwKFFs8tdgjQnX23pegH5KIPw3vZYPwkFJ0gnrDr2nOy/NykTUAQpuUCtHfb0Gi8i10v56q4itwoi/nvm5u1icwohE/d25f50SQ3+wxhCHkgi9LYvGvIynIRfASFMoNktnlRhyhCUF68OLB2hbOHxrqxz68fQDhDjVx/C4P4WayqgLSQ8G79bhrtpsDKGOYDGzGtxZijyE3CgZuCiceHMOeFSTssetauB72k7fqKXxqKAwExG/iCQWi8qQ3V3Fo94UJD2FlpIfZ0QBBISh80ZfmSSZeVxK0OvdFM4MeaZr7OGKKIhOb+M9dJJB7lD9xpLP3DCL0GOjzSwgePucoUGJqauCIOrizRU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Sir-John-Oldcastle_1788
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy